[package]
name = "vdev"
version = "0.1.0"
edition = "2021"
authors = ["Vector Contributors <vector@datadoghq.com>"]
license = "MPL-2.0"
readme = "README.md"
publish = false

[dependencies]
anyhow = "1.0.79"
cached = "0.48.0"
chrono.workspace = true
clap.workspace = true
clap-verbosity-flag = "2.1.2"
clap_complete = "4.4.9"
confy = "0.6.0"
directories = "5.0.1"
# remove this when stabilized https://doc.rust-lang.org/stable/std/path/fn.absolute.html
dunce = "1.0.4"
glob = { version = "0.3.1", default-features = false }
hex = "0.4.3"
indexmap = { version = "2.0", default-features = false, features = ["serde", "std"] }
indicatif = { version = "0.17.7", features = ["improved_unicode"] }
itertools = "0.12.0"
log = "0.4.20"
once_cell = "1.19"
os_info = { version = "3.7.0", default-features = false }
# watch https://github.com/epage/anstyle for official interop with Clap
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
paste = "1.0.14"
regex = { version = "1.10.3", default-features = false, features = ["std", "perf"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
serde_yaml = "0.9.30"
sha2 = "0.10.8"
tempfile = "3.9.0"
toml = { version = "0.8.8", default-features = false, features = ["parse"] }
